"""cascade delete added

Revision ID: d08b6fdfbb3f
Revises: 48203a21b17a
Create Date: 2026-05-21 23:27:56.881969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08b6fdfbb3f'
down_revision: Union[str, Sequence[str], None] = '48203a21b17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('blogs_author_id_fkey'), 'blogs', type_='foreignkey')
    op.create_foreign_key(None, 'blogs', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_foreign_key(op.f('blogs_author_id_fkey'), 'blogs', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###
